### PR TITLE
tests for stat_summary_xy

### PR DESCRIPTION
**Pull request by alexjoerich**

### CODE REVIEW

**Review by aphalo — COMMENTED** [review]
Thanks! These tests look good. You could repeat at least one of them passing the name of the function as a character string, e.g., "mean", and by passing an anonymous function defined within the call. I think this should increase the coverage.

**Comment by alexjoerich** [comment]
Can you explain what you mean by passing an anonymous function defined within the call?

**Review by aphalo — COMMENTED** [review]
Hi. Thanks! This looks good! You could add similar tests for the `.fun.x` parameter (you had included this in one of the first commits). This should help increase the coverage noticeably. If needed to reach high enough test coverage you could also add tests for `.fun.y.args` and `.fun.x.args`, maybe using one of the functions for confidence limits like `mean_sdl()` and passing say `mult = 1` to it as argument.

Renaming the function will not increase coverage, I think, because the name match is done by `do.call()`, however, the additional test does not do any harm. String vs. object name uses different R code to obtain the function name as a string which could slightly improve coverage, and this you have now addressed.

Once you are ready with the suggested changes, I will be happy to merge this pull request.

**Comment by alexjoerich** [comment]
Thanks Pedro will update with suggestions.

**Comment by aphalo** [comment]
Thanks! As this is your first pull request for this repo, I have to trigger GitHub actions mannually. I run them, and I see one test failing. Please, have a look at the test results.

**Review by aphalo — CHANGES_REQUESTED** [review]
Thanks! I run the GitHub actions and I see your pull request failing. (There is an additional failure in the main branch affecting only Mac tests that can safely be ignored.)

**Comment by aphalo** [comment]
@alexjoerich Many thanks! I merged because I wanted to see if we needed more tests for this stats. We still need some. Feel free to make a new pull request if you want to still edit these tests or add new ones.

**Comment by alexjoerich** [comment]
Where can I see the coverage report to know which areas could use more
testing?

**Comment by aphalo** [comment]
@alexjoerich I am using within RStudio in the Addins menue the entry "Report test coverage for a package". It takes some time to run but when it finishes one can see in the "Viewer" pane the result for each file. If you then click on the file name, you will see the lisiting of the file. The lines of code covered by tests are highlighted in green and those that are not covered by tests are highlighted in red.  Usually one can work out from these what argument values one needs to use in tests for these lines of code to be tested.
I have started using this only recently in the latest version of RStudio. I am not sure if this has been available in earlier versions. You will also notice that the value for % coverage calculated within RStudio is a bit different than that reported in GitHub by the action that Danikar added.
The coverage reports from the GitHub action are visible in a separate branch "_xml_coverage_reports" updated automatically by the action Danikar added. All the information is there, but as far as I can see, not in an easy to browse format. Because of this I have use the coverage computed locally within RStudio when working on the code.
Please, do pull the latest commits I pushed yesterday to GitHub. I editted the code of several layer functions to make sure the code is not ignored when coverage is computed. It made a huge difference!
Please, let me know if you have any other questions.

**Pull request merged**
