### PR TITLE
added more tests

### PR DESCRIPTION
**Pull request by sob2021**

### CODE REVIEW

**Comment by danielinteractive** [comment]
Thanks @sob2021 - to add the description for @aphalo, this increases test coverage for `geom_table()` including a missing `nudge_x` argument as well as passing string `left` to the `table_hjust` argument.

**Comment by aphalo** [comment]
Thanks! 

How thoroughly do we need to check the code to both increase coverage and ensure that all important tests are done? In this test you test only one of the several possible justification cases. Do we need to test them all? I think yes, but it would be much more efficient to just test the single internal function that translates justification values from character strings into numeric values, and them in the geometries test fewer cases... The translation from character strings to numerical justification interacts with the angle of rotation, so thoroughly testing this translation in each geometry would bloat the number of test cases needed for the geometries.

The rest of this week I need to work on two manuscritps and to repair a non-functioning environmental cabinet. I think it is anyway more efficient to work on groups or related tests as a group, rather than one or two at a time. My guess is that to reach adequate coverage we will need to add more than 100 new cases and edit several of the existing ones. If you make pull requests with ten or more test cases each, say the whole set of tests for one function, it will be easier for me to see the big picture and give meaninful feedback.

Not to interfere with your work I will restrain from adding new test cases myself for the time being. The little time I have had to work on 'ggpp' I have been using to work on the documentation.

**Comment by danielinteractive** [comment]
Thanks @aphalo for the feedback!

- We will try to group the tests in not too unreasonable batches. We had deliberately kept the first PR very small to see whether it makes sense for you etc., so now we will add more tests into this PR here before re-requesting your review.

- We are adding new tests only for exported functions, i.e. functions which are part of the user interface of the package, and we specifically look at what lines of code were not covered with tests before. E.g. here for `geom_table()` we saw that few lines were not covered yet and we add tests accordingly.

- Regarding tests of internal functions, we will defer this to you as you see needed and fit and you have the expertise to test those.

**Comment by aphalo** [comment]
Thanks! Now I understand your approach, and seems very good. I will prepare tests for internal functions and once you add tests to ensure enough code coverage for the exported functions I will check that the tests also cover reasonably well different valid and invalid user supplied values for arguments.

As part of the pull request(s), do add yourself and other members of your team  to the DESCRIPTION file.  
I mean everyone who makes significant contributions to the pull requests, I think, should be listed as a contributor.

Best wishes,

Pedro.

**Comment by aphalo** [comment]
Could your approach to testing for errors may fail in those cases when the errors are triggered when the plot is rendered? I have usually tried to trigger errors as early as possible but not always managed or even remembered to take this into account. Please, let me know, e,g., raise an issue if you encounter errors triggered too late and I will try to move such tests so they trigger errors earlier, when feasible.

Testing only the value returned by the layer functions looks like a wise trick!! I added today some tests for justification with vdiffr but I intend to revise them. I'll try to use your approach.

**Comment by danielinteractive** [comment]
@aphalo Yeah good question, we will keep watching out for those cases, and let you know immediately when we see one.

**Comment by aphalo** [comment]
@danielinteractive After rethinking the approaches to testing that avoid rendering, I have to say that in geoms a lot of the code is in the compute_group() or compute_panel() functions which are run only during plot rendering. If we want to excercise all/most of the code I cannot think of an alternative to using 'vdiffr'. A potential alternative would be to directly compare grobs, but I think this would only make false positive outcomes even more frequent than with 'vdiffr'.

So, yesterday I ended adding tests to exercise the justification, but using vdiffr. I could not find an alternative way. I edited .buildignore so that folder tests is no longer excluded from the released package. I will soon update the CI scripts in Github as the ones currently in use are out-of-date.

So, with 'vdiffr' we can achieve high code coverage with the tests, but these tests will not be run on CRAN. Would this allow compliance with your requirements for 'ggpp'? or do you need all the tests in the > 80% code coverage to routinely be run on CRAN?

**Comment by danielinteractive** [comment]
@aphalo From our side we are fine if those tests are not run on CRAN. And I would also guess that those `compute_group()` or `compute_panel()` functions are internal, in which case we are not so much concerned regarding test coverage. (Of course for the package quality it will be very good to have these tested with `vdiffr()`, in the future there might be platform variant support added, as I asked them in https://github.com/r-lib/vdiffr/issues/125)

**Review by aphalo — CHANGES_REQUESTED** [review]
One thing I am not sure about is if unique names for the test cases are needed. I have normally included the name of the function being tested, possibliy abbreviated, here geom_table as part of the name, to ensure that names are unique and informative. If you agree, this could be changed before I approve this pull request.

**Comment by danielinteractive** [comment]
@aphalo sure we can try to follow more closely your convention on the tests naming. Also @sob2021 will still add some more tests in this PR, we can then re-request review.

**Comment by aphalo** [comment]
@danielinteractive @sob2021 I pushed several commits between yesterday and today. I updated the CI scripts in GitHub as the old ones were failing to install R (I used package 'usethis' both earlier and now). I did edits to several geoms to address issues #5 and #9. These included changes to the signature needed for consistency among the diffferent geoms. I intend to submit the current code to CRAN in coming days. This will give you a stable code base to work on the tests. The tests could be incorporated to the next release, as soon as they are ready.

**Comment by sob2021** [comment]
Hi @aphalo 
I've added more tests for `geom_table()`, `geom_table_npc()`, `geom_grob()` and `geom_grob_npc()` , for your review.

Thank you.

**Review by aphalo — APPROVED** [review]

**Review by aphalo — APPROVED** [review]
These tests are useful and will run fast. I am happy with them. However, these tests test only the code that builds the "gg" object, not the code in the functions that are saved in the object, including the _draw_panel_ function which runs during rendering of the plot. I am afraid tests like these, will not improve the coverage by much. We may need to rethink how get > 80% test coverage.

I think one possibility would be to test the _draw panel_ functions on their own, but they are internal to the package.

**Review by aphalo — APPROVED** [review]
Thanks for doing the suggested edits.

**Comment by aphalo** [comment]
@sob2021 @danielinteractive This batch of tests is now merged. Many thanks!

**Comment by danielinteractive** [comment]
Thanks a lot @aphalo !
For our purposes, the most important (and required) thing is to get good unit test coverage for the exported functions.
I think testing internal functions would be great in addition - however this will be harder for us, since internal functions tend to be more complicated to call and understand. So I would suggest that you consider adding separate tests for the internal functions. (This is also the approach we take for other R packages in general, where we have tests for all different levels of functions)

**Comment by aphalo** [comment]
@danielinteractive I haven't set up tests before for internal functions. Do you just use testthat as usual or does one need to use the three colon ::: notation even if the tests are part of the package?

**Comment by danielinteractive** [comment]
@aphalo you don't need the `:::` namespacing but you can just use the internal functions in the tests, they are available there.

**Pull request merged**
