### PR TITLE
Tests stat_apply_group and stat_fmt_tb

### PR DESCRIPTION
**Pull request by alexjoerich**
Added unit tests for `stat_apply_group()` and `stat_fmt_tb()`

### CODE REVIEW

**Comment by alexjoerich** [comment]
@aphalo please see new unit tests.

**Review by aphalo — CHANGES_REQUESTED** [review]
In tests/testthat/test-stat_apply_group.R you have an error in line 10: the name of the unsorted data frame on the rhs. Your pull request is not passing unit tests.  Please, fix. Many thanks!

**Comment by alexjoerich** [comment]
Hi @aphalo, please see updated all the unit tests.

**Review by aphalo — APPROVED** [review]
Many thanks! Let's see how much coverage we get.

**Pull request merged**
