### PR TITLE
Test geom quadrant lines

### PR DESCRIPTION
**Pull request by BFalquet**
This PR includes tests for `geom_quadrant_lines`.

thank you for your review and comments.

### CODE REVIEW

**Comment by aphalo** [comment]
Thanks! I cannot follow the logic of the test in lines 45-50. You edit the value returned by the function being tested insted of editing the reference to match the expected value with the additional arguments. This seems to me to be the wrong way around.

Can you please check? Maybe adding a comment would help me understand the intention of the test.

**Comment by BFalquet** [comment]
Thank you @aphalo for your review! I spitted the tests into several blocks, I think that it will make the logic clearer (and create a little bit of redundancy). Cheers

**Review by aphalo — CHANGES_REQUESTED** [review]
Thanks for the edits! I am afraid I need to ask more changes before approval.

You are recreating `tst.df` many times unecessarily. It is enough to define it once, before the first `test_that()` at line 4.

Please, delete lines 51 and 52, as they are not needed.

Line 97, please, change:
`"geom_vhlines returns an error neither x nor y intercepts are not provided"`
into
`"geom_vhlines returns an error if neither x nor y intercept is provided"`

In line 119, you could change
`"geom_vhlines works as expected with custom parameter values"`
into
`"geom_vhlines works as expected with multiple intercepts"`

**Review by aphalo — APPROVED** [review]
Thanks!

**Pull request merged**
